name: Continuous Integration

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - develop

  workflow_call:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Set up JDK 11 job has success
        if: ${{ success() }}
        run: echo "ğŸ‰ Set up JDK 11 job has success"

      - name: Set up AWS CI bot IAM
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Set up resources/** secrets from s3 bucket
        run: aws s3 cp --region ap-northeast-2 --acl private s3://hr-backend-secret-properties-bucket/application-resource-secret/ ./src/main/resources --recursive

      - name: Set up secret resources success ğŸ‰
        if: ${{ success() }}
        run: echo "ğŸ‰ Set up secret resources success"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run build with Gradle wrapper
        run: ./gradlew build --scan

      - name: Upload build reports
        uses: actions/upload-artifact@v3
        with:
          name: build-reports
          path: build/reports/

       - name: Unit Test Results
         uses: EnricoMi/publish-unit-test-result-action@v1
         if: ${{ always() }}
         with:
           files: build/test-results/**/*.xml

      - name: Build with Gradle job has success
        if: ${{ success() }}
        run: echo "ğŸ‰ Build with Gradle job has success"

      - name: Make app zip folder
        run: zip -r hirecruit-backend-test *
        shell: bash

      - name: Upload zip to S3
        run: aws s3 cp --region ap-northeast-2 hirecruit-backend-test.zip s3://hr-backend-zip

      - name: HiRecruit Backend CI success Discord Notification
        uses: sarisia/actions-status-discord@v1
        if: ${{ success() }}
        with:
          title: ğŸ‰ HiRecruit Backend CI success ğŸ‰
          webhook: ${{ secrets.DISCORD_WEBHOOK_CI_BOT }}
          color: 00FF00

      - name: HiRecruit Backend CI failure Discord Notification
        uses: sarisia/actions-status-discord@v1
        if: ${{ failure() }}
        with:
          title: âŒ HiRecruit Backend CI failed âŒ
          webhook: ${{ secrets.DISCORD_WEBHOOK_CI_BOT }}
          color: FF0000
